(function(){"use strict";
var shell=document.getElementById("sentinelShell"),launcher=document.getElementById("sentinelLauncher"),history=document.getElementById("sentinelHistory"),replies=document.getElementById("sentinelReplies"),form=document.getElementById("sentinelForm"),input=document.getElementById("sentinelInput"),access=document.getElementById("sentinelAccessNote"),previousFocus,briefStep=-1,briefAnswers=[];
if(!shell||!history||!form||!input)return;
var pathways=[
{terms:["website","web design","performance"],answer:"A high-performance website pathway usually starts with a content and conversion audit, then information architecture, accessible interface design, implementation, and measured launch validation.",source:["Web design service","web-design.html"],replies:["What platform do you use?","Start a project brief","Talk to a human"]},
{terms:["lead","seo","growth"],answer:"For qualified growth, ClearGlass can connect positioning, technical SEO, conversion paths, analytics, and responsible automation. We first identify the audience and meaningful conversion—without inventing traffic or outcome guarantees.",source:["Services & engagements","offers/index.html"],replies:["Who are your ideal users?","Start a project brief","View services"]},
{terms:["ai","automation","agent"],answer:"The AI automation pathway maps the workflow, data boundaries, model and tool permissions, evaluations, approval gates, observability, and rollback before production enablement. Consequential actions remain human-supervised.",source:["AI automation services","#services"],replies:["What workflow should improve?","How do approval gates work?","Start a project brief"]},
{terms:["portal","application","app"],answer:"A secure portal engagement begins with user roles, data classification, tenant boundaries, authentication, authorization, audit requirements, and the smallest useful workflow. Interface restrictions alone are never treated as authorization.",source:["ClearGlass capabilities","#services"],replies:["Who will use the portal?","What integrations are needed?","Start a project brief"]},
{terms:["cyber","security","incident","alert","threat"],answer:"ClearGlass provides blue-team-aligned cybersecurity guidance: risk and control mapping, exposure reduction, detection priorities, zero-trust architecture, and incident readiness. This public concierge cannot inspect systems or confirm an incident; sensitive or urgent matters should be escalated to an authorized human.",source:["Cybersecurity & risk","#services"],replies:["Talk to a human","How is sensitive data handled?","Start a project brief"]},
{terms:["cloud","deploy","devops","hosting"],answer:"A cloud deployment pathway covers workload boundaries, CI/CD controls, least-privilege identity, environment protection, observability, recovery, and rollback. Recommendations depend on your stack, availability needs, and compliance constraints.",source:["Enterprise architecture","#services"],replies:["What stack do you use?","What uptime do you need?","Start a project brief"]},
{terms:["price","cost","budget"],answer:"I will not invent pricing or availability. Approved engagement information is on the pricing and services pages, and a human can confirm a scoped estimate after discovery.",source:["Published pricing","pricing.html"],replies:["View pricing","Talk to a human","Start a project brief"]}
];
var questions=["What are you trying to build or improve?","What does your current website or platform use?","What is the main business goal, and who are the users?","What integrations are required?","What timeline are you considering?","Which constraints matter most—budget, performance, accessibility, privacy, security, or compliance?","Do you need ongoing support, and what level of security or compliance review is expected?"];
function addMessage(text,actor,source){var item=document.createElement("article"),avatar=document.createElement("span"),body=document.createElement("div"),copy=document.createElement("p");item.className="sentinel-message sentinel-message--"+actor;avatar.className="sentinel-message-avatar";avatar.setAttribute("aria-hidden","true");avatar.textContent=actor==="user"?"YOU":"S";body.className="sentinel-message-body";copy.textContent=text;body.appendChild(copy);if(actor==="assistant"){var meta=document.createElement("div");meta.className="sentinel-message-meta";meta.appendChild(document.createTextNode("Confidence: "+(source?"High":"General guidance")+" · Source: "));if(source){var link=document.createElement("a");link.href=source[1];link.textContent=source[0];meta.appendChild(link)}else meta.appendChild(document.createTextNode("Sentinel policy"));body.appendChild(meta)}item.append(avatar,body);history.appendChild(item);history.scrollTop=history.scrollHeight}
function setReplies(labels){replies.replaceChildren();labels.forEach(function(label){var button=document.createElement("button");button.type="button";button.textContent=label;button.addEventListener("click",function(){handleMessage(label)});replies.appendChild(button)})}
function welcome(){if(history.children.length)return;addMessage("Hello—I’m ClearGlass Sentinel, an automated AI concierge. I can explain services, shape a project pathway, or connect you with a human. I cannot access systems or activate support and blue-team modes from this public page. What would you like to strengthen?","assistant");setReplies(["Explore services","Start a project brief","Cybersecurity guidance","Talk to a human"])}
function openPanel(prompt){previousFocus=document.activeElement;shell.hidden=false;document.body.classList.add("sentinel-open");welcome();shell.querySelector("[data-sentinel-close]").focus();if(prompt)handleMessage(prompt)}
function closePanel(){shell.hidden=true;document.body.classList.remove("sentinel-open");if(previousFocus&&previousFocus.focus)previousFocus.focus()}
function startBrief(){briefStep=0;briefAnswers=[];addMessage("Let’s create a private draft in this browser. Please do not include credentials or sensitive records. "+questions[0],"assistant");setReplies(["I need a website","I need automation","I need security guidance"])}
function continueBrief(message){briefAnswers.push(message);briefStep++;if(briefStep<questions.length){addMessage(questions[briefStep],"assistant");setReplies(["Skip this question","Talk to a human"])}else{addMessage("Your draft brief is ready. Nothing has been submitted. Review it, remove sensitive details, then choose “Talk to a human” to contact ClearGlass and explicitly decide what to share.","assistant");setReplies(["Talk to a human","Clear conversation","Explore services"])}}
function handleMessage(raw){var message=String(raw||"").trim().slice(0,800);if(!message)return;addMessage(message,"user");var normalized=message.toLowerCase();if(/password|api[ -]?key|secret key|credit card|card number|private key|credential/.test(normalized)){addMessage("Please do not share that information. I have not transmitted or stored this conversation. Remove sensitive data and contact an authorized ClearGlass human through a verified channel if support is required.","assistant");setReplies(["Talk to a human","Clear conversation"]);return}if(normalized.includes("talk to a human")){addMessage("Use the “Talk to a human” link below to open your email client. You choose what to send; Sentinel does not submit this conversation automatically.","assistant");setReplies(["Start a project brief","Explore services"]);return}if(normalized.includes("clear conversation")){history.replaceChildren();replies.replaceChildren();briefStep=-1;briefAnswers=[];welcome();return}if(briefStep>=0){continueBrief(message);return}if(normalized.includes("start a project brief")){startBrief();return}if(normalized.includes("view pricing")){location.href="pricing.html";return}if(normalized.includes("view services")||normalized==="explore services"){location.href="offers/index.html";return}var match=pathways.find(function(p){return p.terms.some(function(term){return normalized.includes(term)})});if(match){addMessage(match.answer,"assistant",match.source);setReplies(match.replies);return}addMessage("I can help with web design, web applications, AI automation, cybersecurity, DevOps, SEO, cloud deployment, and governed growth infrastructure. For legal, financial, sensitive, or incident-specific decisions, I will route you to a human rather than guess.","assistant");setReplies(["Explore services","Start a project brief","Talk to a human"])}
document.querySelectorAll("[data-sentinel-open]").forEach(function(b){b.addEventListener("click",function(){openPanel()})});document.querySelectorAll("[data-sentinel-prompt]").forEach(function(b){b.addEventListener("click",function(){openPanel(b.dataset.sentinelPrompt)})});document.querySelectorAll("[data-sentinel-close]").forEach(function(b){b.addEventListener("click",closePanel)});document.querySelector("[data-sentinel-dismiss]").addEventListener("click",function(){launcher.hidden=true;try{sessionStorage.setItem("cg-sentinel-dismissed","true")}catch(e){}});document.querySelector("[data-sentinel-access]").addEventListener("click",function(){access.hidden=!access.hidden});document.querySelector("[data-sentinel-brief]").addEventListener("click",startBrief);document.querySelector("[data-sentinel-clear]").addEventListener("click",function(){history.replaceChildren();replies.replaceChildren();briefStep=-1;briefAnswers=[];welcome()});form.addEventListener("submit",function(e){e.preventDefault();var message=input.value;input.value="";handleMessage(message)});input.addEventListener("keydown",function(e){if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();form.requestSubmit()}});
shell.addEventListener("keydown",function(e){if(e.key==="Escape"){closePanel();return}if(e.key!=="Tab")return;var all=Array.from(shell.querySelectorAll("button,a[href],textarea")).filter(function(el){return el.offsetParent!==null});if(!all.length)return;var first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});try{if(sessionStorage.getItem("cg-sentinel-dismissed")==="true")launcher.hidden=true}catch(e){}
}());
