"""PERCIVAL · PFAS — evidence pack exporter (Markdown + JSON).

Renders a ``CompliancePackage`` (from ``pfas.screen``) as either:
  * a downloadable JSON evidence pack (``export_json``), or
  * a client-ready Markdown report (``export_markdown``).

Defensive, stdlib-only. The exporter never *creates* findings — it only
formats what ``pfas.screen`` already produced. A denied package still exports
faithfully so the rationale and audit_ref are preserved.
"""
from __future__ import annotations

import datetime as _dt
import json

from .pfas import HC_25_PFAS_NGL, CompliancePackage


def _safe_id(s: str | None) -> str:
    s = (s or "package").strip()
    return "".join(c if (c.isalnum() or c in "-_") else "-" for c in s) or "package"


def export_json(pkg: CompliancePackage, *, indent: int = 2) -> str:
    """Stable, machine-readable JSON representation of the package."""
    return json.dumps(pkg.to_dict(), indent=indent, sort_keys=True)


def export_markdown(pkg: CompliancePackage, *,
                    title: str = "PERCIVAL · PFAS Compliance Package") -> str:
    """Client-ready Markdown rendering. Honest about denials: a refused
    package emits the reasons + audit_ref instead of fabricating a finding."""
    now = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    out: list[str] = [
        f"# {title}",
        "",
        f"- **Generated (UTC):** {pkg.generated_utc or now}",
        f"- **Audit ref:** `{pkg.audit_ref or '—'}`",
        f"- **Sample id:** `{pkg.sample_id or '—'}`",
        f"- **Threshold:** {HC_25_PFAS_NGL:g} ng/L (sum of 25 PFAS, Health Canada interim)",
        "",
    ]

    if not pkg.accepted:
        out += [
            "## Status",
            "",
            "**DENIED — fail-closed.**",
            "",
            "### Reasons",
            "",
            *(f"- {r}" for r in pkg.reasons),
            "",
        ]
    else:
        f = pkg.finding
        if f is None:
            out += ["## Status", "", "**ACCEPTED**, but no finding produced.", ""]
        else:
            out += [
                "## Top line",
                "",
                f"- **Risk band:** **{f.risk.value}**",
                f"- **Sum of 25 (ng/L):** {f.sum_25_ngL:.2f} (upper bound {f.sum_25_ngL_max:.2f})",
                f"- **% of threshold:** {(f.exceedance_ratio * 100):.0f}%",
                f"- **Matrix:** {f.matrix}",
                "",
                "## Detected analytes",
                "",
                ("- " + ", ".join(f.detected_analytes)) if f.detected_analytes
                else "- _(none ≥ LOQ)_",
                "",
                "## Likely source categories (informational)",
                "",
                *(f"- {h}" for h in f.source_category_hints),
                "",
            ]

        if pkg.next_actions:
            out += ["## Next actions", "",
                    *(f"- [ ] {a}" for a in pkg.next_actions), ""]
        if pkg.resample_after_days is not None:
            out += [f"**Resample after:** {pkg.resample_after_days} days", ""]
        if pkg.treatment_options:
            out += ["## Treatment options to evaluate", "",
                    *(f"- {t}" for t in pkg.treatment_options), ""]

    if pkg.references:
        out += ["## References", "", *(f"- {r}" for r in pkg.references), ""]

    out += [
        "---",
        "*Generated by PERCIVAL · PFAS. Asset-focused compliance intelligence; "
        "no personal data processed.*",
    ]
    return "\n".join(out) + "\n"


def package_filename(pkg: CompliancePackage, ext: str) -> str:
    """Stable, audit-traceable filename for a saved evidence pack."""
    return f"pfas-{_safe_id(pkg.sample_id)}-{_safe_id(pkg.audit_ref)}.{ext}"
