variable "aws_region" {
  description = "AWS region for all resources"
  type        = string
  default     = "us-east-1"
}

variable "aws_account_id" {
  description = "AWS account ID"
  type        = string
  default     = "206478392741"
}

variable "github_org" {
  description = "GitHub organization name"
  type        = string
  default     = "ClearGlassInc"
}

variable "github_app_id" {
  description = "GitHub App ID (set via TF_VAR_github_app_id or SSM — bootstrap.sh handles this)"
  type        = string
  sensitive   = true
}

variable "github_app_key_base64" {
  description = "GitHub App private key base64-encoded (bootstrap.sh sets this)"
  type        = string
  sensitive   = true
}

variable "github_app_webhook_secret" {
  description = "GitHub App webhook secret (auto-generated by bootstrap.sh)"
  type        = string
  sensitive   = true
  default     = ""  # overridden by random_password resource
}

variable "runner_instance_types" {
  description = "EC2 instance types for runners — spot market picks cheapest available"
  type        = list(string)
  default     = ["m5.large", "m4.large", "c5.large", "c4.large", "t3.large"]
}

variable "runner_volume_size_gb" {
  description = "Root EBS volume size in GB for each runner"
  type        = number
  default     = 30
}

variable "runner_max_instances" {
  description = "Hard cap on concurrent runners (cost safety)"
  type        = number
  default     = 5
}

variable "environment" {
  description = "Deployment environment tag"
  type        = string
  default     = "production"
}
