# Copyright (c) 2024-2026 ClearGlass Inc. All Rights Reserved.
# Proprietary and confidential. See LICENSE for terms.
"""Alert dispatcher bot.

Reads bot output files, detects failures and anomalies, writes a consolidated
alert manifest. Creates a GitHub Issue for critical alerts when GITHUB_TOKEN
is available.
"""
from __future__ import annotations

import json
import os
import sys
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.error import URLError
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / "operations" / "output"

GITHUB_REPO = "clearglassinc/clearglassinc.github.io"
GITHUB_API = "https://api.github.com"
CONSECUTIVE_FAILURE_THRESHOLD = 3


@dataclass
class Alert:
    severity: str  # "critical" | "warning" | "info"
    source: str
    message: str
    detail: str
    detected_utc: str


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _check_site_health(data: dict[str, Any]) -> list[Alert]:
    alerts: list[Alert] = []
    if data.get("overall_healthy"):
        return alerts

    unreachable = data.get("pages_unreachable", 0)
    if unreachable > 0:
        bad = [p["path"] for p in data.get("pages", []) if not p.get("reachable")]
        alerts.append(Alert(
            severity="critical", source="site_health",
            message=f"{unreachable} page(s) unreachable: {', '.join(bad)}",
            detail=json.dumps(bad), detected_utc=_now(),
        ))

    for issue in data.get("local_issues", []):
        alerts.append(Alert(
            severity="warning", source="site_health",
            message=issue, detail="", detected_utc=_now(),
        ))

    return alerts


def _check_orchestrator(data: dict[str, Any]) -> list[Alert]:
    alerts: list[Alert] = []
    failed_count = data.get("failed", 0)
    if failed_count == 0:
        return alerts

    failed_bots = [b["bot_id"] for b in data.get("bots", []) if b.get("status") == "error"]
    alerts.append(Alert(
        severity="warning", source="orchestrator",
        message=f"{failed_count} bot(s) failed: {', '.join(failed_bots)}",
        detail=json.dumps(failed_bots), detected_utc=_now(),
    ))
    return alerts


def _check_run_log(entries: list[dict[str, Any]]) -> list[Alert]:
    alerts: list[Alert] = []
    recent = entries[-50:]

    # Count consecutive failures per bot (looking at last N entries per bot)
    bot_recent_statuses: dict[str, list[str]] = {}
    for entry in recent:
        bot = entry.get("bot", "unknown")
        bot_recent_statuses.setdefault(bot, []).append(entry.get("status", ""))

    for bot, statuses in bot_recent_statuses.items():
        tail = statuses[-CONSECUTIVE_FAILURE_THRESHOLD:]
        if len(tail) >= CONSECUTIVE_FAILURE_THRESHOLD and all(s == "error" for s in tail):
            alerts.append(Alert(
                severity="critical", source="run_log",
                message=f"Bot '{bot}' failed {CONSECUTIVE_FAILURE_THRESHOLD}+ times in a row",
                detail=f"Last {len(tail)} statuses: {tail}",
                detected_utc=_now(),
            ))

    return alerts


def _create_github_issue(alerts: list[Alert]) -> bool:
    token = os.getenv("GITHUB_TOKEN", "").strip()
    if not token:
        return False

    critical = [a for a in alerts if a.severity == "critical"]
    if not critical:
        return False

    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    title = f"[ALERT] {len(critical)} critical system alert(s) — {date_str}"

    rows = "\n".join(
        f"| {'🔴' if a.severity == 'critical' else '🟡'} {a.severity} | `{a.source}` | {a.message} |"
        for a in alerts
    )
    body = (
        "## 🚨 Critical Alerts Detected\n\n"
        f"**Detected:** {_now()}\n\n"
        "| Severity | Source | Message |\n"
        "|----------|--------|---------|\n"
        f"{rows}\n\n"
        "---\n"
        "*Auto-generated by ClearGlass Alert Dispatcher Bot*"
    )

    payload = json.dumps({"title": title, "body": body, "labels": ["alert", "automated"]}).encode()
    req = Request(
        f"{GITHUB_API}/repos/{GITHUB_REPO}/issues",
        data=payload,
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
        method="POST",
    )

    try:
        with urlopen(req, timeout=15) as resp:
            return resp.status == 201
    except (URLError, Exception):  # noqa: BLE001
        return False


def run() -> dict[str, Any]:
    alerts: list[Alert] = []

    health_path = OUTPUT_DIR / "site_health_report.json"
    if health_path.exists():
        try:
            alerts.extend(_check_site_health(json.loads(health_path.read_text())))
        except Exception:  # noqa: BLE001
            pass

    orch_path = OUTPUT_DIR / "orchestrator_summary.json"
    if orch_path.exists():
        try:
            alerts.extend(_check_orchestrator(json.loads(orch_path.read_text())))
        except Exception:  # noqa: BLE001
            pass

    log_path = OUTPUT_DIR / "bot_run_log.json"
    if log_path.exists():
        try:
            log_data = json.loads(log_path.read_text())
            if isinstance(log_data, list):
                alerts.extend(_check_run_log(log_data))
        except Exception:  # noqa: BLE001
            pass

    issue_created = False
    if alerts:
        issue_created = _create_github_issue(alerts)

    manifest: dict[str, Any] = {
        "run_utc": _now(),
        "total_alerts": len(alerts),
        "critical": sum(1 for a in alerts if a.severity == "critical"),
        "warnings": sum(1 for a in alerts if a.severity == "warning"),
        "github_issue_created": issue_created,
        "alerts": [asdict(a) for a in alerts],
    }

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUTPUT_DIR / "alerts.json").write_text(json.dumps(manifest, indent=2))

    return manifest


def main() -> None:
    manifest = run()
    total = manifest["total_alerts"]
    critical = manifest["critical"]

    if total == 0:
        print("Alert Dispatcher: No alerts detected")
        return

    print(f"Alert Dispatcher: {total} alert(s), {critical} critical")
    if manifest["github_issue_created"]:
        print("GitHub Issue created for critical alerts")

    if critical > 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
