"use client";
import { Component, type ErrorInfo, type PropsWithChildren, type ReactNode } from "react";
import type { ConnectionState, DataFreshness, Signal } from "@/lib/contracts";

export type LiveViewProps = { state: ConnectionState; freshness?: DataFreshness; reducedMotion?: boolean; accessibilityLabel?: string; empty?: boolean };
export function LiveConnectionIndicator({ state, accessibilityLabel = "Live data connection" }: LiveViewProps) { return <span className={`connection connection--${state.toLowerCase()}`} role="status" aria-label={`${accessibilityLabel}: ${state.toLowerCase()}`}><i aria-hidden="true" />{state}</span>; }
export function LiveDataBadge({ freshness }: Pick<LiveViewProps, "freshness">) { return <span className="badge">{freshness?.state === "live" ? "Live now" : freshness?.state === "cached" ? "Cached snapshot" : freshness?.state === "stale" ? "Stale data" : freshness?.state === "estimated" ? "Estimate" : freshness?.state === "recent" ? "Recently measured" : "Unavailable"}</span>; }
export function LastUpdatedLabel({ freshness }: Pick<LiveViewProps, "freshness">) { const stamp = freshness?.receivedAt ?? freshness?.measuredAt; return <time dateTime={stamp}>{stamp ? `Last verified ${new Date(stamp).toLocaleString()}` : "No verified measurement available"}</time>; }
export function StaleDataNotice({ state }: Pick<LiveViewProps, "state">) { return state === "STALE" || state === "DEGRADED" ? <p className="notice" role="status">The stream is degraded. The last verified snapshot remains visible.</p> : null; }
export function LiveMetricCard({ signal, state }: { signal?: Signal; state: ConnectionState }) { return <article className="metric"><div><p>{signal?.label ?? "Signal unavailable"}</p><LiveDataBadge freshness={signal?.freshness} /></div><strong>{signal?.value ?? "Not configured"}</strong><LastUpdatedLabel freshness={signal?.freshness} /><span className="sr-only">Connection {state}</span></article>; }
export function LiveSignalGrid({ signals, state }: { signals: Signal[]; state: ConnectionState }) { return <div className="signal-grid">{signals.length ? signals.map((signal) => <LiveMetricCard key={signal.key} signal={signal} state={state} />) : <LiveMetricCard state={state} />}</div>; }
export function LiveActivityTimeline({ events = [] }: { events?: Array<{ id: string; label: string; time: string }> }) { return <ol className="timeline">{events.length ? events.map((event) => <li key={event.id}><time dateTime={event.time}>{event.time}</time>{event.label}</li>) : <li>No verified public activity is available.</li>}</ol>; }
export function LiveStatusBanner({ state }: Pick<LiveViewProps, "state">) { return <div className="status-banner"><strong>ClearGlass Live Signal Fabric</strong><span>{state === "DISABLED" ? "Production streams are disabled pending approval." : `Connection state: ${state}`}</span></div>; }
export const LivePerformancePanel = LiveSignalGrid;
export function LiveSystemMap({ signals, state }: { signals: Signal[]; state: ConnectionState }) { return <section aria-label="System signal map" className="system-map"><span>Verified source</span><span aria-hidden="true">→</span><span>Signal fabric</span><span aria-hidden="true">→</span><span>{signals.length ? `${signals.length} approved signals` : state === "DISABLED" ? "Disabled" : "Unavailable"}</span></section>; }
export function LiveEventStream({ event }: { event?: { type: string; publishedAt: string } }) { return <div className="event-stream" aria-live="polite">{event ? `${event.type} received at ${event.publishedAt}` : "No validated events received."}</div>; }
export function LiveReconnectButton({ onRetry, disabled = false }: { onRetry: () => void; disabled?: boolean }) { return <button type="button" onClick={onRetry} disabled={disabled}>Reconnect</button>; }
export function LiveDataConsentControl({ enabled, onChange }: { enabled: boolean; onChange: (next: boolean) => void }) { return <label className="toggle"><input type="checkbox" checked={enabled} onChange={(e) => onChange(e.target.checked)} />Allow privacy-safe live updates</label>; }
export const LiveStreamToggle = LiveDataConsentControl;
export class LiveErrorBoundary extends Component<PropsWithChildren, { failed: boolean }> { state = { failed: false }; static getDerivedStateFromError() { return { failed: true }; } componentDidCatch(_error: Error, _info: ErrorInfo) {} render(): ReactNode { return this.state.failed ? <div role="alert">This live module is unavailable. Static page content remains available.</div> : this.props.children; } }
