from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from typing import Any


def canonical_hash(payload: dict[str, Any]) -> str:
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def create_manifest(
    source: str,
    publisher: str,
    license_name: str,
    query_parameters: dict[str, Any],
) -> dict[str, Any]:
    manifest = {
        "source": source,
        "publisher": publisher,
        "license": license_name,
        "retrieved_at": datetime.now(timezone.utc).isoformat(),
        "query_parameters": query_parameters,
        "processing_version": "0.1.0",
        "confidence": "source-derived",
        "limitations": [],
        "notes": "Generated by OSIT provenance service.",
    }
    manifest["sha256"] = canonical_hash(manifest)
    return manifest
