// Product detail page. Copy is generated by the Catalog & Content agent (draft → approved).
export default function ProductPage({ params }: { params: { slug: string } }) {
  return (
    <article>
      <a href="/" style={{ color: "#9aa6c8" }}>
        ← Back
      </a>
      <h1 style={{ fontSize: 30, marginTop: 12 }}>{params.slug}</h1>
      <p style={{ color: "#9aa6c8" }}>
        Description rendered from <code>content_assets</code>. Claims are verified — no fabricated
        reviews or scarcity.
      </p>
      <button
        style={{
          marginTop: 16,
          padding: "12px 22px",
          borderRadius: 10,
          border: "1px solid rgba(124,150,255,.3)",
          background: "linear-gradient(180deg,rgba(124,150,255,.3),rgba(124,150,255,.08))",
          color: "#fff",
          cursor: "pointer",
        }}
      >
        Add to cart
      </button>
    </article>
  );
}
