"use client";

// Product detail page with a working checkout. Copy is generated by the Catalog
// & Content agent (draft → approved); pricing comes from the governed catalog.
import { useState } from "react";
import { createCheckout } from "@/lib/api";
import { findProduct, formatPrice } from "@/lib/catalog";
import { AddToCart } from "@/lib/AddToCart";

export default function ProductPage({ params }: { params: { slug: string } }) {
  const product = findProduct(params.slug);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function buy() {
    if (!product) return;
    setLoading(true);
    setError(null);
    try {
      const session = await createCheckout([
        {
          name: product.title,
          amount: product.amount,
          quantity: 1,
          currency: product.currency,
        },
      ]);
      // Redirect to Stripe Checkout (live) or the mock success URL (dev/CI).
      window.location.href = session.url;
    } catch (e) {
      setError(e instanceof Error ? e.message : "Checkout failed — please try again.");
      setLoading(false);
    }
  }

  return (
    <article>
      <a href="/" style={{ color: "#9aa6c8" }}>
        ← Back
      </a>
      <h1 style={{ fontSize: 30, marginTop: 12 }}>{product ? product.title : params.slug}</h1>
      <p style={{ color: "#9aa6c8" }}>
        {product
          ? product.blurb
          : "Description rendered from content_assets. Claims are verified — no fabricated reviews or scarcity."}
      </p>
      {product && (
        <div style={{ fontSize: 22, color: "#a78bfa", marginTop: 8 }}>
          {formatPrice(product.amount, product.currency)}
        </div>
      )}
      <div style={{ display: "flex", gap: 12, alignItems: "center", flexWrap: "wrap" }}>
        <button
          onClick={buy}
          disabled={!product || loading}
          style={{
            marginTop: 16,
            padding: "12px 22px",
            borderRadius: 10,
            border: "1px solid rgba(124,150,255,.3)",
            background: "linear-gradient(180deg,rgba(124,150,255,.3),rgba(124,150,255,.08))",
            color: "#fff",
            cursor: !product || loading ? "not-allowed" : "pointer",
            opacity: !product || loading ? 0.6 : 1,
          }}
        >
          {loading ? "Starting checkout…" : "Buy now"}
        </button>
        {product && <AddToCart product={product} />}
      </div>
      {error && (
        <p role="alert" style={{ color: "#f87171", marginTop: 12 }}>
          {error}
        </p>
      )}
    </article>
  );
}
