import { PageFlow } from "../../components/layout/PageFlow";
import { SystemSection } from "../../components/layout/SystemSection";
export const metadata = { title: "Self-Improvement Loop | ClearGlassInc Artemis", description: "Safe, evaluated, human-approved intelligence-system improvement." };
export default function LearningPage() { return <PageFlow route="/learning" eyebrow="Self-improvement loop" title="Every improvement is a proposal—not a privilege." summary="Operator signals become versioned evaluation evidence. Artemis can recommend prompt, routing, heuristic, or workflow changes, but only people can authorize promotion through controlled release gates.">
  <nav className="section-nav" aria-label="On this page"><a href="#signals">Signals</a><a href="#promotion">Promotion gates</a><a href="#metrics">Evaluation</a></nav>
  <SystemSection id="signals" title="Signal capture" intro="Privacy-aware telemetry distinguishes observed outcomes from subjective feedback and prevents popularity from becoming ground truth." items={[
    { title: "Operator feedback", text: "Accept, reject, edit distance, correction category, rationale, confidence, role, mission phase, and time-to-decision." }, { title: "Operational outcomes", text: "Alert disposition, investigation result, downstream reversal, predicted-versus-observed effect, and delayed outcome window." }, { title: "System behavior", text: "Retrieval coverage, tool errors, policy denials, abstentions, token and cost budget, latency, and model-route decisions." }, { title: "Eval candidate", text: "A de-identified, access-controlled case with frozen inputs, expected properties, rubric, cohort tags, and adjudication state." },
  ]} />
  <SystemSection id="promotion" title="Controlled promotion" intro="The loop is deliberately asymmetric: proposing is easy; earning deployment authority requires independent evidence." items={[
    { title: "1 · Diagnose", text: "Drift monitors segment failures by mission, source, language, classification, model, prompt, and operator cohort." }, { title: "2 · Propose", text: "A candidate includes a bounded diff, hypothesis, affected workflows, threat analysis, expected gain, and rollback trigger." }, { title: "3 · Evaluate", text: "Frozen regression, adversarial, safety, calibration, latency, and cost suites compare candidate against the champion." }, { title: "4 · Approve", text: "Model, prompt, policy, data, and operational owners review applicable changes; agents cannot satisfy this gate." }, { title: "5 · Canary", text: "Apollo stages an immutable release to an authorized cohort with kill switches and no silent champion fallback." }, { title: "6 · Observe or roll back", text: "Predefined guardrails either promote gradually or restore the last known-good bundle and open an incident record." },
  ]} />
  <SystemSection id="metrics" title="Evaluation contract" intro="No single score can authorize promotion; safety and policy regressions are hard failures." items={[
    { title: "Quality", text: "Precision, recall, citation entailment, evidence coverage, calibration error, false-negative severity, and abstention quality." }, { title: "Operations", text: "Time-to-insight, p50/p95/p99 latency, queue age, completion rate, workload reduction, reversals, and mission outcome proxies." }, { title: "Trust and safety", text: "Operator trust by cohort, override rate, policy violations, leakage tests, prompt-injection resistance, and audit completeness." },
  ]} />
</PageFlow>; }
