import {Dashboard} from "@/components/Dashboard";import {RoiCalculator} from "@/components/RoiCalculator";import {Pricing} from "@/components/Pricing";
const pains=[["A renewal date is missed","You keep paying for a tool nobody uses."],["An agreement disappears","The team cannot find terms, responsibilities, or renewal conditions when it matters."],["Nobody owns the vendor","Important requests wait because accountability is unclear."],["Spreadsheets stop scaling","Information becomes incomplete, outdated, and difficult to trust."]];
const features=[["Vendor Command Center","See every vendor, owner, cost, and next step without chasing updates."],["Agreement and Document Register","Keep the record and its essential details together so the team can find it quickly."],["Renewal Intelligence","Put notice windows and renewal decisions on the calendar before they become surprises."],["Owner and Accountability Mapping","Give every relationship and obligation a clear person responsible for moving it forward."],["Approval Workflows","Route decisions to the right reviewer and keep the outcome visible to the team."],["Ready-to-Use Operations Templates","Start with practical workflows instead of designing your process from scratch."]];
const steps=[["Add what matters.","Import vendors, agreements, renewal dates, and key documents from the tools you already use."],["Assign ownership.","Make the right person accountable for each vendor, obligation, renewal, or approval."],["Stay ahead.","Receive reminders, surface work that needs attention, and create a reliable operational rhythm."],["Grow with control.","Add workflows and visibility when your business gets more complex."]];
const faqs=[["Is Procurement Legal Tech legal advice?","No. Procurement Legal Tech is an operational organization tool. It does not provide legal, tax, procurement, cybersecurity, or compliance advice."],["Who is this built for?","Founders and operations leads at 5–50 person businesses, agencies, consultants, and growing teams managing vendors and agreements without an enterprise procurement department."],["Can I start without a credit card?","Yes. The 14-day trial requires no credit card and creates a starter workspace with sample records and a guided checklist."],["Can I cancel my subscription online?","Yes. The intended subscription experience includes online cancellation. Final cancellation and refund terms require owner approval before commerce is activated."],["Can I upgrade or downgrade later?","Yes. Plan changes are designed to be self-serve, with the effective date and billing impact shown before confirmation."],["Are taxes included in the displayed price?","No. Prices are in Canadian dollars; applicable taxes are added at checkout."],["Can I import from spreadsheets?","Yes. Every plan includes CSV import and export. Optional assisted migration is available only when selected."],["How are renewal reminders handled?","Add a renewal date and notice window, choose recipients, and receive email reminders before action is due."],["How do user limits work?","Control supports 3 users, Oversight 15, and Command 50. Access is managed per workspace."],["What happens after my trial ends?","If you do not choose a paid plan, paid features do not activate and no card is charged. Final data-retention terms require owner approval."],["Can I get help setting up my workspace?","Yes. Guided setup and migration are optional paid services shown only after plan selection."],["How is my information protected?","The target implementation uses role-based access, encryption in transit, secure authentication practices, activity records, and account controls. Production claims remain disabled until verified."]];
const rows=[["Vendor directory","Included","Included","Included"],["Document register","Included","Included","Included"],["Renewal reminders","Email","Email + calendar","Automated"],["Workspace members","3","15","50"],["Owner assignment","—","Included","Included"],["Approval workflows","—","Included","Advanced"],["Activity history","—","Included","Included"],["Reporting","Basic","Standard","Advanced"],["Custom templates","—","—","Included"],["Audit-log export","—","—","Included"],["Onboarding","Self-serve","Self-serve","Priority session"],["Support level","Community/email","Priority email","Priority"]];
export default function Home(){return <main id="main"><section className="hero"><div className="hero-copy"><p className="eyebrow">Operational clarity for growing businesses</p><h1>Your vendors, agreements, renewals, and responsibilities—finally in one place.</h1><p>Procurement Legal Tech gives small teams a simple command center for tracking the business commitments that are too important to leave in spreadsheets, inboxes, and someone’s memory.</p><div className="actions"><a className="primary" href="#pricing">Build your free workspace</a><a className="secondary" href="#how">See how it works</a></div><p className="micro">No credit card. Setup in minutes. Cancel anytime.</p></div><Dashboard/></section>
<section className="section"><div className="section-head"><p className="kicker">The cost of scattered work</p><h2>Small operational misses become expensive business problems.</h2></div><div className="grid four">{pains.map(([h,p],i)=><article className="card" key={h}><span className="number">0{i+1}</span><h3>{h}</h3><p>{p}</p></article>)}</div></section>
<section className="section"><div className="section-head"><p className="kicker">A calmer operating system</p><h2>One source of operational truth.</h2><p>Bring the records your business depends on into one understandable view.</p></div><div className="grid three">{features.map(([h,p])=><article className="card" key={h}><h3>{h}</h3><p>{p}</p></article>)}</div></section>
<section className="section" id="how"><div className="section-head"><p className="kicker">How it works</p><h2>From scattered records to a system your team can trust.</h2></div><div className="grid four workflow">{steps.map(([h,p])=><article className="card" key={h}><h3>{h}</h3><p>{p}</p></article>)}</div></section>
<section className="section"><div className="section-head"><p className="kicker">Operational exposure estimator</p><h2>See what scattered information may be costing you.</h2></div><RoiCalculator/></section>
<section className="section" id="pricing"><div className="section-head"><p className="kicker">14 days free · no credit card</p><h2>Simple pricing for operational control.</h2><p>Start small. Upgrade only when your workflow needs more structure.</p></div><Pricing/></section>
<section className="section"><div className="section-head"><p className="kicker">Compare plans</p><h2>Clear limits. No feature maze.</h2></div><div className="table-wrap"><table className="comparison"><caption>Plan feature comparison</caption><thead><tr><th scope="col">Feature</th><th scope="col">Control</th><th scope="col">Oversight</th><th scope="col">Command</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><th scope="row">{r[0]}</th>{r.slice(1).map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></div></section>
<section className="section" id="security"><div className="security"><div><p className="kicker">Trust by design</p><h2>Built to keep operational information organized and access-controlled.</h2><p>These are target implementation controls. Public security claims remain disabled until the owner verifies production evidence.</p></div><ul><li>Role-based workspace access</li><li>Encryption in transit</li><li>Secure authentication practices</li><li>Activity records for key workspace actions</li><li>Privacy controls and account-management tools</li></ul></div></section>
<section className="section faq"><div className="section-head"><p className="kicker">Questions, answered</p><h2>What to know before you start.</h2></div>{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
<section className="section"><div className="final"><p className="kicker">Start with clarity</p><h2>Get control before another renewal, agreement, or approval gets lost.</h2><p>Create a workspace in minutes and give your team one reliable place to manage the obligations that keep your business moving.</p><a className="primary" href="#pricing">Start free for 14 days</a><p className="micro">No credit card required. Cancel anytime.</p></div></section></main>}
