#!/usr/bin/env python3
# Copyright (c) 2024-2026 ClearGlass Inc. All Rights Reserved.
# Proprietary and confidential. See LICENSE for terms.
"""Create the daily Marketing Content GitHub issue from generated content.

The historical daily workflow produced one GitHub issue per generated content
bundle labeled ``campaign:daily``.  This script restores that handoff: it reads
``marketing/output/latest.json`` and ``latest.md``, builds a deterministic issue
title/body, creates the labels if they do not exist, and opens the issue via
GitHub CLI.  Duplicate protection is date-based so reruns update the log without
spamming operators.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import shutil
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
LATEST_JSON = ROOT / "marketing" / "output" / "latest.json"
LATEST_MD = ROOT / "marketing" / "output" / "latest.md"
ISSUE_LABELS = ["campaign:daily", "content", "platform:multi", "stage:idea", "automation"]


def _run(cmd: list[str], *, check: bool = True) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
    if check and result.returncode != 0:
        print(result.stdout, end="")
        print(result.stderr, end="", file=sys.stderr)
        raise SystemExit(result.returncode)
    return result


def _load_bundle() -> dict[str, Any]:
    if not LATEST_JSON.exists() or not LATEST_MD.exists():
        raise SystemExit(
            "Generated content is missing. Run `python -m bots.content_engine` first."
        )
    return json.loads(LATEST_JSON.read_text(encoding="utf-8"))


def _issue_title(bundle: dict[str, Any]) -> str:
    run_dt = datetime.fromisoformat(bundle["run_utc"].replace("Z", "+00:00"))
    date = run_dt.astimezone(timezone.utc).date().isoformat()
    pillar = str(bundle.get("pillar", "content")).replace("_", " ").title()
    short_hash = str(bundle.get("content_hash", "nohash"))[:12]
    return f"Marketing Content: {pillar} · {date} · {short_hash}"


def _issue_body(bundle: dict[str, Any]) -> str:
    latest_md = LATEST_MD.read_text(encoding="utf-8").strip()
    platforms = ", ".join(p.get("platform", "unknown") for p in bundle.get("platforms", []))
    return "\n".join([
        "## Daily Marketing Content Workflow",
        "",
        "Automated daily content package generated by the ClearGlassInc bot orchestrator.",
        "",
        "### Run metadata",
        f"- Run UTC: `{bundle.get('run_utc')}`",
        f"- Pillar: `{bundle.get('pillar')}`",
        f"- ISO week: `{bundle.get('iso_week')}`",
        f"- Variant index: `{bundle.get('variant_index')}`",
        f"- Content hash: `{bundle.get('content_hash')}`",
        f"- Platforms: `{platforms}`",
        "",
        "### Operator checklist",
        "- [ ] Review copy for accuracy and brand fit.",
        "- [ ] Approve, edit, or reject each platform draft.",
        "- [ ] Schedule approved posts in the publishing tool.",
        "- [ ] Record performance notes for tomorrow's iteration.",
        "",
        "---",
        "",
        latest_md,
        "",
    ])


def _ensure_labels(repo: str) -> None:
    colors = {
        "campaign:daily": "7057ff",
        "content": "1d76db",
        "platform:multi": "0e8a16",
        "stage:idea": "fbca04",
        "automation": "c5def5",
    }
    for label in ISSUE_LABELS:
        _run([
            "gh", "label", "create", label,
            "--repo", repo,
            "--color", colors.get(label, "ededed"),
            "--description", "Daily marketing content workflow label",
            "--force",
        ], check=False)


def _existing_issue(repo: str, date: str) -> str | None:
    query = f'state:open label:"campaign:daily" "{date}" in:title'
    result = _run([
        "gh", "issue", "list", "--repo", repo,
        "--search", query,
        "--json", "number",
        "--jq", ".[0].number // empty",
    ], check=False)
    number = result.stdout.strip()
    return number or None


def _repo_from_git_remote() -> str:
    result = _run(["git", "config", "--get", "remote.origin.url"], check=False)
    remote = result.stdout.strip()
    if remote.startswith("git@github.com:"):
        return remote.removeprefix("git@github.com:").removesuffix(".git")
    if "github.com/" in remote:
        return remote.split("github.com/", 1)[1].removesuffix(".git")
    return ""


def _resolve_repo() -> str:
    repo = os.getenv("GITHUB_REPOSITORY") or _repo_from_git_remote()
    if repo:
        return repo
    if shutil.which("gh"):
        return _run(
            ["gh", "repo", "view", "--json", "nameWithOwner", "--jq", ".nameWithOwner"],
            check=False,
        ).stdout.strip()
    return ""


def create_issue(dry_run: bool = False) -> int:
    repo = _resolve_repo()
    if not repo:
        raise SystemExit("Unable to determine GitHub repository. Set GITHUB_REPOSITORY.")

    bundle = _load_bundle()
    title = _issue_title(bundle)
    body = _issue_body(bundle)
    date = datetime.fromisoformat(bundle["run_utc"].replace("Z", "+00:00")).date().isoformat()

    print(f"Issue title: {title}")
    if dry_run:
        print(body[:2000])
        return 0
    if not shutil.which("gh"):
        raise SystemExit("GitHub CLI (`gh`) is required to create the issue.")

    _ensure_labels(repo)
    existing = _existing_issue(repo, date)
    if existing:
        print(f"Daily marketing issue already open for {date}: #{existing}")
        return 0

    with tempfile.NamedTemporaryFile("w", encoding="utf-8", delete=False) as fh:
        fh.write(body)
        body_path = fh.name
    try:
        _run([
            "gh", "issue", "create", "--repo", repo,
            "--title", title,
            "--body-file", body_path,
            "--label", ",".join(ISSUE_LABELS),
        ])
    finally:
        Path(body_path).unlink(missing_ok=True)
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(description="Create the daily marketing content issue")
    parser.add_argument("--dry-run", action="store_true", help="Print issue payload without creating it")
    args = parser.parse_args()
    raise SystemExit(create_issue(dry_run=args.dry_run))


if __name__ == "__main__":
    main()
