-- ClearGlass Minerals Intelligence Platform baseline
-- PostgreSQL 16 + PostGIS 3.4
-- UUID values using Prisma @default(uuid()) are generated by Prisma Client.

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TYPE "RecordStatus" AS ENUM ('VERIFIED','DELAYED','ESTIMATED','ANALYST','DEMO','UNKNOWN');
CREATE TYPE "ProjectStage" AS ENUM ('CONCEPT','EXPLORATION','DEVELOPMENT','CONSTRUCTION','OPERATING','CARE_MAINTENANCE','CLOSED','UNKNOWN');
CREATE TYPE "FacilityType" AS ENUM ('PROCESSOR','REFINERY','SMELTER','CONCENTRATOR','MANUFACTURING','STORAGE','OTHER');
CREATE TYPE "LogisticsType" AS ENUM ('PORT','RAIL_TERMINAL','AIRPORT','BORDER_CROSSING','WAREHOUSE','OTHER');
CREATE TYPE "RiskSeverity" AS ENUM ('LOW','MODERATE','HIGH','CRITICAL','UNKNOWN');
CREATE TYPE "AlertStatus" AS ENUM ('OPEN','ACKNOWLEDGED','ASSIGNED','RESOLVED','SUPPRESSED');
CREATE TYPE "UserRole" AS ENUM ('VIEWER','ANALYST','SENIOR_ANALYST','DATA_STEWARD','ADMINISTRATOR','API_CLIENT');

CREATE TABLE "Mineral" (
  "id" UUID NOT NULL,
  "slug" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "symbol" TEXT,
  "group" TEXT,
  "description" TEXT,
  "endUses" JSONB,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "deletedAt" TIMESTAMP(3),
  CONSTRAINT "Mineral_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "MineralForm" (
  "id" UUID NOT NULL,
  "mineralId" UUID NOT NULL,
  "name" TEXT NOT NULL,
  "grade" TEXT,
  "formType" TEXT,
  "unit" TEXT,
  "description" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "MineralForm_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Country" (
  "id" UUID NOT NULL,
  "iso2" VARCHAR(2) NOT NULL,
  "iso3" VARCHAR(3) NOT NULL,
  "name" TEXT NOT NULL,
  "region" TEXT,
  "subregion" TEXT,
  "sanctionsTag" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Country_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Jurisdiction" (
  "id" UUID NOT NULL,
  "countryId" UUID NOT NULL,
  "name" TEXT NOT NULL,
  "code" TEXT,
  "level" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Jurisdiction_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Company" (
  "id" UUID NOT NULL,
  "name" TEXT NOT NULL,
  "ticker" TEXT,
  "exchange" TEXT,
  "website" TEXT,
  "countryCode" TEXT,
  "lei" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "deletedAt" TIMESTAMP(3),
  CONSTRAINT "Company_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Deposit" (
  "id" UUID NOT NULL,
  "name" TEXT NOT NULL,
  "depositType" TEXT,
  "geology" JSONB,
  "location" geography(Point,4326),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Deposit_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Project" (
  "id" UUID NOT NULL,
  "name" TEXT NOT NULL,
  "aliases" TEXT[] NOT NULL,
  "externalIds" JSONB,
  "stage" "ProjectStage" NOT NULL DEFAULT 'UNKNOWN',
  "countryId" UUID,
  "jurisdictionId" UUID,
  "operatorId" UUID,
  "depositId" UUID,
  "mineralId" UUID,
  "location" geography(Point,4326),
  "latitude" DOUBLE PRECISION,
  "longitude" DOUBLE PRECISION,
  "capacityValue" DECIMAL(20,6),
  "capacityUnit" TEXT,
  "permitStatus" TEXT,
  "transportNotes" TEXT,
  "sourceStatus" "RecordStatus" NOT NULL DEFAULT 'UNKNOWN',
  "confidence" DECIMAL(5,4),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "deletedAt" TIMESTAMP(3),
  CONSTRAINT "Project_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Mine" (
  "id" UUID NOT NULL,
  "name" TEXT NOT NULL,
  "aliases" TEXT[] NOT NULL,
  "externalIds" JSONB,
  "stage" "ProjectStage" NOT NULL DEFAULT 'UNKNOWN',
  "countryId" UUID,
  "jurisdictionId" UUID,
  "operatorId" UUID,
  "depositId" UUID,
  "mineralId" UUID,
  "location" geography(Point,4326),
  "latitude" DOUBLE PRECISION,
  "longitude" DOUBLE PRECISION,
  "mineLifeYears" DECIMAL(10,2),
  "processingMethod" TEXT,
  "permitStatus" TEXT,
  "sourceStatus" "RecordStatus" NOT NULL DEFAULT 'UNKNOWN',
  "confidence" DECIMAL(5,4),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "deletedAt" TIMESTAMP(3),
  CONSTRAINT "Mine_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Facility" (
  "id" UUID NOT NULL,
  "name" TEXT NOT NULL,
  "type" "FacilityType" NOT NULL,
  "countryId" UUID,
  "operatorId" UUID,
  "location" geography(Point,4326),
  "latitude" DOUBLE PRECISION,
  "longitude" DOUBLE PRECISION,
  "commodities" JSONB,
  "capacity" JSONB,
  "sourceStatus" "RecordStatus" NOT NULL DEFAULT 'UNKNOWN',
  "confidence" DECIMAL(5,4),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "deletedAt" TIMESTAMP(3),
  CONSTRAINT "Facility_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "OwnershipRelationship" (
  "id" UUID NOT NULL,
  "ownerCompanyId" UUID NOT NULL,
  "mineId" UUID,
  "projectId" UUID,
  "sharePercent" DECIMAL(8,4),
  "relationship" TEXT,
  "verified" BOOLEAN NOT NULL DEFAULT false,
  "validFrom" TIMESTAMP(3),
  "validTo" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "OwnershipRelationship_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ProductionRecord" (
  "id" UUID NOT NULL,
  "mineralId" UUID NOT NULL,
  "mineId" UUID,
  "countryId" UUID,
  "periodStart" TIMESTAMP(3) NOT NULL,
  "periodEnd" TIMESTAMP(3) NOT NULL,
  "value" DECIMAL(24,8) NOT NULL,
  "unit" TEXT NOT NULL,
  "status" "RecordStatus" NOT NULL DEFAULT 'VERIFIED',
  "confidence" DECIMAL(5,4),
  "sourceId" UUID,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ProductionRecord_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ReserveResourceEstimate" (
  "id" UUID NOT NULL,
  "mineralId" UUID NOT NULL,
  "mineId" UUID,
  "estimateType" TEXT NOT NULL,
  "classification" TEXT,
  "asOf" TIMESTAMP(3) NOT NULL,
  "value" DECIMAL(24,8) NOT NULL,
  "unit" TEXT NOT NULL,
  "grade" DECIMAL(16,8),
  "gradeUnit" TEXT,
  "status" "RecordStatus" NOT NULL DEFAULT 'VERIFIED',
  "confidence" DECIMAL(5,4),
  "sourceId" UUID,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ReserveResourceEstimate_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "PriceSeries" (
  "id" UUID NOT NULL,
  "mineralId" UUID NOT NULL,
  "benchmark" TEXT NOT NULL,
  "market" TEXT,
  "timestamp" TIMESTAMP(3) NOT NULL,
  "value" DECIMAL(24,8) NOT NULL,
  "currency" VARCHAR(3) NOT NULL,
  "unit" TEXT NOT NULL,
  "status" "RecordStatus" NOT NULL DEFAULT 'VERIFIED',
  "confidence" DECIMAL(5,4),
  "sourceId" UUID,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PriceSeries_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "TradeRecord" (
  "id" UUID NOT NULL,
  "mineralId" UUID NOT NULL,
  "originCountryId" UUID NOT NULL,
  "destinationCountryId" UUID NOT NULL,
  "periodStart" TIMESTAMP(3) NOT NULL,
  "periodEnd" TIMESTAMP(3) NOT NULL,
  "hsCode" TEXT,
  "quantity" DECIMAL(24,8),
  "quantityUnit" TEXT,
  "tradeValue" DECIMAL(24,2),
  "currency" VARCHAR(3),
  "unitPrice" DECIMAL(24,8),
  "status" "RecordStatus" NOT NULL DEFAULT 'VERIFIED',
  "confidence" DECIMAL(5,4),
  "sourceId" UUID,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "TradeRecord_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "LogisticsNode" (
  "id" UUID NOT NULL,
  "name" TEXT NOT NULL,
  "type" "LogisticsType" NOT NULL,
  "countryId" UUID,
  "location" geography(Point,4326),
  "latitude" DOUBLE PRECISION,
  "longitude" DOUBLE PRECISION,
  "attributes" JSONB,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "LogisticsNode_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ShippingRoute" (
  "id" UUID NOT NULL,
  "originNodeId" UUID NOT NULL,
  "destinationNodeId" UUID NOT NULL,
  "mode" TEXT NOT NULL,
  "geometry" geography(LineString,4326),
  "verified" BOOLEAN NOT NULL DEFAULT false,
  "attributes" JSONB,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "ShippingRoute_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "RiskAssessment" (
  "id" UUID NOT NULL,
  "mineId" UUID,
  "projectId" UUID,
  "score" DECIMAL(6,2),
  "severity" "RiskSeverity" NOT NULL DEFAULT 'UNKNOWN',
  "methodologyVersion" TEXT NOT NULL,
  "observedAt" TIMESTAMP(3) NOT NULL,
  "confidence" DECIMAL(5,4),
  "analystOverride" BOOLEAN NOT NULL DEFAULT false,
  "overrideReason" TEXT,
  "createdById" UUID,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "RiskAssessment_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "RiskFactor" (
  "id" UUID NOT NULL,
  "assessmentId" UUID NOT NULL,
  "key" TEXT NOT NULL,
  "score" DECIMAL(6,2),
  "weight" DECIMAL(6,4) NOT NULL,
  "explanation" TEXT,
  "evidence" JSONB,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "RiskFactor_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Organization" (
  "id" UUID NOT NULL,
  "name" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "settings" JSONB,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "deletedAt" TIMESTAMP(3),
  CONSTRAINT "Organization_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "User" (
  "id" UUID NOT NULL,
  "email" TEXT NOT NULL,
  "name" TEXT,
  "subject" TEXT,
  "disabled" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Alert" (
  "id" UUID NOT NULL,
  "organizationId" UUID,
  "type" TEXT NOT NULL,
  "severity" "RiskSeverity" NOT NULL,
  "status" "AlertStatus" NOT NULL DEFAULT 'OPEN',
  "title" TEXT NOT NULL,
  "body" TEXT,
  "dedupeKey" TEXT,
  "entityType" TEXT,
  "entityId" TEXT,
  "threshold" JSONB,
  "assignedToId" UUID,
  "acknowledgedAt" TIMESTAMP(3),
  "resolvedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Alert_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Watchlist" (
  "id" UUID NOT NULL,
  "organizationId" UUID NOT NULL,
  "ownerId" UUID NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Watchlist_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "WatchlistItem" (
  "id" UUID NOT NULL,
  "watchlistId" UUID NOT NULL,
  "entityType" TEXT NOT NULL,
  "entityId" TEXT NOT NULL,
  "label" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "WatchlistItem_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "DataSource" (
  "id" UUID NOT NULL,
  "key" TEXT NOT NULL,
  "provider" TEXT NOT NULL,
  "dataset" TEXT NOT NULL,
  "sourceUrl" TEXT,
  "license" TEXT,
  "restrictions" TEXT,
  "geographicCoverage" JSONB,
  "cadence" TEXT,
  "ttlSeconds" INTEGER,
  "enabled" BOOLEAN NOT NULL DEFAULT true,
  "lastSuccessAt" TIMESTAMP(3),
  "lastAttemptAt" TIMESTAMP(3),
  "freshnessStatus" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "DataSource_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Event" (
  "id" UUID NOT NULL,
  "type" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "summary" TEXT,
  "occurredAt" TIMESTAMP(3) NOT NULL,
  "jurisdiction" TEXT,
  "entityType" TEXT,
  "entityId" TEXT,
  "status" "RecordStatus" NOT NULL DEFAULT 'VERIFIED',
  "confidence" DECIMAL(5,4),
  "sourceId" UUID,
  "metadata" JSONB,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Event_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "SourceDocument" (
  "id" UUID NOT NULL,
  "sourceId" UUID,
  "title" TEXT NOT NULL,
  "url" TEXT,
  "reference" TEXT,
  "publishedAt" TIMESTAMP(3),
  "collectedAt" TIMESTAMP(3) NOT NULL,
  "contentHash" TEXT,
  "license" TEXT,
  "status" "RecordStatus" NOT NULL DEFAULT 'VERIFIED',
  "metadata" JSONB,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "SourceDocument_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "IngestionRun" (
  "id" UUID NOT NULL,
  "sourceId" UUID NOT NULL,
  "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "finishedAt" TIMESTAMP(3),
  "status" TEXT NOT NULL,
  "recordsRead" INTEGER NOT NULL DEFAULT 0,
  "recordsWritten" INTEGER NOT NULL DEFAULT 0,
  "recordsRejected" INTEGER NOT NULL DEFAULT 0,
  "retryCount" INTEGER NOT NULL DEFAULT 0,
  "transformLog" JSONB,
  "error" TEXT,
  CONSTRAINT "IngestionRun_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "ProvenanceRecord" (
  "id" UUID NOT NULL,
  "sourceId" UUID,
  "documentId" UUID,
  "entityType" TEXT NOT NULL,
  "entityId" TEXT NOT NULL,
  "field" TEXT,
  "sourceReference" TEXT,
  "collectedAt" TIMESTAMP(3) NOT NULL,
  "transformedAt" TIMESTAMP(3),
  "confidence" DECIMAL(5,4),
  "calculationMethod" TEXT,
  "license" TEXT,
  "analystReviewedAt" TIMESTAMP(3),
  "analystReviewerId" UUID,
  "status" "RecordStatus" NOT NULL DEFAULT 'VERIFIED',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ProvenanceRecord_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "AnalystAnnotation" (
  "id" UUID NOT NULL,
  "organizationId" UUID NOT NULL,
  "authorId" UUID NOT NULL,
  "entityType" TEXT NOT NULL,
  "entityId" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "visibility" TEXT NOT NULL DEFAULT 'organization',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "deletedAt" TIMESTAMP(3),
  CONSTRAINT "AnalystAnnotation_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "SavedView" (
  "id" UUID NOT NULL,
  "organizationId" UUID NOT NULL,
  "ownerId" UUID NOT NULL,
  "name" TEXT NOT NULL,
  "state" JSONB NOT NULL,
  "isShared" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "SavedView_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Report" (
  "id" UUID NOT NULL,
  "organizationId" UUID NOT NULL,
  "authorId" UUID NOT NULL,
  "title" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "body" JSONB NOT NULL,
  "sourceSnapshot" JSONB,
  "generatedByAi" BOOLEAN NOT NULL DEFAULT false,
  "reviewedAt" TIMESTAMP(3),
  "publishedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Report_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "OrganizationMember" (
  "id" UUID NOT NULL,
  "organizationId" UUID NOT NULL,
  "userId" UUID NOT NULL,
  "role" "UserRole" NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "OrganizationMember_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "AuditLog" (
  "id" UUID NOT NULL,
  "organizationId" UUID,
  "userId" UUID,
  "action" TEXT NOT NULL,
  "entityType" TEXT,
  "entityId" TEXT,
  "ipHash" TEXT,
  "userAgent" TEXT,
  "metadata" JSONB,
  "previousHash" TEXT,
  "entryHash" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);

-- Unique constraints
CREATE UNIQUE INDEX "Mineral_slug_key" ON "Mineral"("slug");
CREATE UNIQUE INDEX "MineralForm_mineralId_name_key" ON "MineralForm"("mineralId","name");
CREATE UNIQUE INDEX "Country_iso2_key" ON "Country"("iso2");
CREATE UNIQUE INDEX "Country_iso3_key" ON "Country"("iso3");
CREATE UNIQUE INDEX "Country_name_key" ON "Country"("name");
CREATE UNIQUE INDEX "Jurisdiction_countryId_name_key" ON "Jurisdiction"("countryId","name");
CREATE UNIQUE INDEX "Organization_slug_key" ON "Organization"("slug");
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "User_subject_key" ON "User"("subject");
CREATE UNIQUE INDEX "DataSource_key_key" ON "DataSource"("key");
CREATE UNIQUE INDEX "Watchlist_organizationId_name_key" ON "Watchlist"("organizationId","name");
CREATE UNIQUE INDEX "WatchlistItem_watchlistId_entityType_entityId_key" ON "WatchlistItem"("watchlistId","entityType","entityId");
CREATE UNIQUE INDEX "RiskFactor_assessmentId_key_key" ON "RiskFactor"("assessmentId","key");
CREATE UNIQUE INDEX "SavedView_organizationId_ownerId_name_key" ON "SavedView"("organizationId","ownerId","name");
CREATE UNIQUE INDEX "OrganizationMember_organizationId_userId_key" ON "OrganizationMember"("organizationId","userId");

-- Query indexes
CREATE INDEX "Mineral_name_idx" ON "Mineral"("name");
CREATE INDEX "Mineral_group_idx" ON "Mineral"("group");
CREATE INDEX "Company_name_idx" ON "Company"("name");
CREATE INDEX "Company_ticker_idx" ON "Company"("ticker");
CREATE INDEX "Project_name_idx" ON "Project"("name");
CREATE INDEX "Project_stage_idx" ON "Project"("stage");
CREATE INDEX "Project_countryId_mineralId_idx" ON "Project"("countryId","mineralId");
CREATE INDEX "Mine_name_idx" ON "Mine"("name");
CREATE INDEX "Mine_stage_idx" ON "Mine"("stage");
CREATE INDEX "Mine_countryId_mineralId_idx" ON "Mine"("countryId","mineralId");
CREATE INDEX "Facility_type_countryId_idx" ON "Facility"("type","countryId");
CREATE INDEX "OwnershipRelationship_ownerCompanyId_idx" ON "OwnershipRelationship"("ownerCompanyId");
CREATE INDEX "ProductionRecord_mineralId_periodStart_idx" ON "ProductionRecord"("mineralId","periodStart");
CREATE INDEX "ReserveResourceEstimate_mineralId_asOf_idx" ON "ReserveResourceEstimate"("mineralId","asOf");
CREATE INDEX "PriceSeries_mineralId_benchmark_timestamp_idx" ON "PriceSeries"("mineralId","benchmark","timestamp");
CREATE INDEX "TradeRecord_mineralId_periodStart_idx" ON "TradeRecord"("mineralId","periodStart");
CREATE INDEX "TradeRecord_originCountryId_destinationCountryId_idx" ON "TradeRecord"("originCountryId","destinationCountryId");
CREATE INDEX "LogisticsNode_type_countryId_idx" ON "LogisticsNode"("type","countryId");
CREATE INDEX "ShippingRoute_originNodeId_destinationNodeId_idx" ON "ShippingRoute"("originNodeId","destinationNodeId");
CREATE INDEX "RiskAssessment_observedAt_severity_idx" ON "RiskAssessment"("observedAt","severity");
CREATE INDEX "Alert_organizationId_status_severity_idx" ON "Alert"("organizationId","status","severity");
CREATE INDEX "Alert_dedupeKey_idx" ON "Alert"("dedupeKey");
CREATE INDEX "Event_occurredAt_type_idx" ON "Event"("occurredAt","type");
CREATE INDEX "SourceDocument_publishedAt_idx" ON "SourceDocument"("publishedAt");
CREATE INDEX "SourceDocument_contentHash_idx" ON "SourceDocument"("contentHash");
CREATE INDEX "IngestionRun_sourceId_startedAt_idx" ON "IngestionRun"("sourceId","startedAt");
CREATE INDEX "ProvenanceRecord_entityType_entityId_idx" ON "ProvenanceRecord"("entityType","entityId");
CREATE INDEX "AnalystAnnotation_entityType_entityId_idx" ON "AnalystAnnotation"("entityType","entityId");
CREATE INDEX "Report_organizationId_createdAt_idx" ON "Report"("organizationId","createdAt");
CREATE INDEX "OrganizationMember_userId_role_idx" ON "OrganizationMember"("userId","role");
CREATE INDEX "AuditLog_organizationId_createdAt_idx" ON "AuditLog"("organizationId","createdAt");
CREATE INDEX "AuditLog_action_createdAt_idx" ON "AuditLog"("action","createdAt");

-- Spatial indexes explicitly added because PostGIS fields are Unsupported in Prisma schema language.
CREATE INDEX "Deposit_location_gist" ON "Deposit" USING GIST ("location");
CREATE INDEX "Project_location_gist" ON "Project" USING GIST ("location");
CREATE INDEX "Mine_location_gist" ON "Mine" USING GIST ("location");
CREATE INDEX "Facility_location_gist" ON "Facility" USING GIST ("location");
CREATE INDEX "LogisticsNode_location_gist" ON "LogisticsNode" USING GIST ("location");
CREATE INDEX "ShippingRoute_geometry_gist" ON "ShippingRoute" USING GIST ("geometry");

-- Foreign keys
ALTER TABLE "MineralForm" ADD CONSTRAINT "MineralForm_mineralId_fkey" FOREIGN KEY ("mineralId") REFERENCES "Mineral"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Jurisdiction" ADD CONSTRAINT "Jurisdiction_countryId_fkey" FOREIGN KEY ("countryId") REFERENCES "Country"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Project" ADD CONSTRAINT "Project_countryId_fkey" FOREIGN KEY ("countryId") REFERENCES "Country"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Project" ADD CONSTRAINT "Project_jurisdictionId_fkey" FOREIGN KEY ("jurisdictionId") REFERENCES "Jurisdiction"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Project" ADD CONSTRAINT "Project_operatorId_fkey" FOREIGN KEY ("operatorId") REFERENCES "Company"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Project" ADD CONSTRAINT "Project_depositId_fkey" FOREIGN KEY ("depositId") REFERENCES "Deposit"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Project" ADD CONSTRAINT "Project_mineralId_fkey" FOREIGN KEY ("mineralId") REFERENCES "Mineral"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Mine" ADD CONSTRAINT "Mine_countryId_fkey" FOREIGN KEY ("countryId") REFERENCES "Country"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Mine" ADD CONSTRAINT "Mine_jurisdictionId_fkey" FOREIGN KEY ("jurisdictionId") REFERENCES "Jurisdiction"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Mine" ADD CONSTRAINT "Mine_operatorId_fkey" FOREIGN KEY ("operatorId") REFERENCES "Company"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Mine" ADD CONSTRAINT "Mine_depositId_fkey" FOREIGN KEY ("depositId") REFERENCES "Deposit"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Mine" ADD CONSTRAINT "Mine_mineralId_fkey" FOREIGN KEY ("mineralId") REFERENCES "Mineral"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Facility" ADD CONSTRAINT "Facility_countryId_fkey" FOREIGN KEY ("countryId") REFERENCES "Country"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Facility" ADD CONSTRAINT "Facility_operatorId_fkey" FOREIGN KEY ("operatorId") REFERENCES "Company"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "OwnershipRelationship" ADD CONSTRAINT "OwnershipRelationship_ownerCompanyId_fkey" FOREIGN KEY ("ownerCompanyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "OwnershipRelationship" ADD CONSTRAINT "OwnershipRelationship_mineId_fkey" FOREIGN KEY ("mineId") REFERENCES "Mine"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "OwnershipRelationship" ADD CONSTRAINT "OwnershipRelationship_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ProductionRecord" ADD CONSTRAINT "ProductionRecord_mineralId_fkey" FOREIGN KEY ("mineralId") REFERENCES "Mineral"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProductionRecord" ADD CONSTRAINT "ProductionRecord_mineId_fkey" FOREIGN KEY ("mineId") REFERENCES "Mine"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ProductionRecord" ADD CONSTRAINT "ProductionRecord_countryId_fkey" FOREIGN KEY ("countryId") REFERENCES "Country"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ProductionRecord" ADD CONSTRAINT "ProductionRecord_sourceId_fkey" FOREIGN KEY ("sourceId") REFERENCES "DataSource"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ReserveResourceEstimate" ADD CONSTRAINT "ReserveResourceEstimate_mineralId_fkey" FOREIGN KEY ("mineralId") REFERENCES "Mineral"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ReserveResourceEstimate" ADD CONSTRAINT "ReserveResourceEstimate_mineId_fkey" FOREIGN KEY ("mineId") REFERENCES "Mine"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ReserveResourceEstimate" ADD CONSTRAINT "ReserveResourceEstimate_sourceId_fkey" FOREIGN KEY ("sourceId") REFERENCES "DataSource"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "PriceSeries" ADD CONSTRAINT "PriceSeries_mineralId_fkey" FOREIGN KEY ("mineralId") REFERENCES "Mineral"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PriceSeries" ADD CONSTRAINT "PriceSeries_sourceId_fkey" FOREIGN KEY ("sourceId") REFERENCES "DataSource"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TradeRecord" ADD CONSTRAINT "TradeRecord_mineralId_fkey" FOREIGN KEY ("mineralId") REFERENCES "Mineral"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TradeRecord" ADD CONSTRAINT "TradeRecord_originCountryId_fkey" FOREIGN KEY ("originCountryId") REFERENCES "Country"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TradeRecord" ADD CONSTRAINT "TradeRecord_destinationCountryId_fkey" FOREIGN KEY ("destinationCountryId") REFERENCES "Country"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TradeRecord" ADD CONSTRAINT "TradeRecord_sourceId_fkey" FOREIGN KEY ("sourceId") REFERENCES "DataSource"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "LogisticsNode" ADD CONSTRAINT "LogisticsNode_countryId_fkey" FOREIGN KEY ("countryId") REFERENCES "Country"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ShippingRoute" ADD CONSTRAINT "ShippingRoute_originNodeId_fkey" FOREIGN KEY ("originNodeId") REFERENCES "LogisticsNode"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ShippingRoute" ADD CONSTRAINT "ShippingRoute_destinationNodeId_fkey" FOREIGN KEY ("destinationNodeId") REFERENCES "LogisticsNode"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "RiskAssessment" ADD CONSTRAINT "RiskAssessment_mineId_fkey" FOREIGN KEY ("mineId") REFERENCES "Mine"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "RiskAssessment" ADD CONSTRAINT "RiskAssessment_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "RiskAssessment" ADD CONSTRAINT "RiskAssessment_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "RiskFactor" ADD CONSTRAINT "RiskFactor_assessmentId_fkey" FOREIGN KEY ("assessmentId") REFERENCES "RiskAssessment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Alert" ADD CONSTRAINT "Alert_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Alert" ADD CONSTRAINT "Alert_assignedToId_fkey" FOREIGN KEY ("assignedToId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Watchlist" ADD CONSTRAINT "Watchlist_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Watchlist" ADD CONSTRAINT "Watchlist_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "WatchlistItem" ADD CONSTRAINT "WatchlistItem_watchlistId_fkey" FOREIGN KEY ("watchlistId") REFERENCES "Watchlist"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Event" ADD CONSTRAINT "Event_sourceId_fkey" FOREIGN KEY ("sourceId") REFERENCES "DataSource"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SourceDocument" ADD CONSTRAINT "SourceDocument_sourceId_fkey" FOREIGN KEY ("sourceId") REFERENCES "DataSource"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "IngestionRun" ADD CONSTRAINT "IngestionRun_sourceId_fkey" FOREIGN KEY ("sourceId") REFERENCES "DataSource"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProvenanceRecord" ADD CONSTRAINT "ProvenanceRecord_sourceId_fkey" FOREIGN KEY ("sourceId") REFERENCES "DataSource"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ProvenanceRecord" ADD CONSTRAINT "ProvenanceRecord_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "SourceDocument"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ProvenanceRecord" ADD CONSTRAINT "ProvenanceRecord_analystReviewerId_fkey" FOREIGN KEY ("analystReviewerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AnalystAnnotation" ADD CONSTRAINT "AnalystAnnotation_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AnalystAnnotation" ADD CONSTRAINT "AnalystAnnotation_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SavedView" ADD CONSTRAINT "SavedView_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SavedView" ADD CONSTRAINT "SavedView_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Report" ADD CONSTRAINT "Report_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Report" ADD CONSTRAINT "Report_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "OrganizationMember" ADD CONSTRAINT "OrganizationMember_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OrganizationMember" ADD CONSTRAINT "OrganizationMember_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
