import { PageFlow } from "../../components/layout/PageFlow";
import { SystemSection } from "../../components/layout/SystemSection";
export const metadata = { title: "Security & Governance | ClearGlassInc Artemis", description: "Zero-trust, coalition-aware governance architecture." };
export default function GovernancePage() { return <PageFlow route="/governance" eyebrow="Security and governance" title="Need-to-know is computed at every boundary." summary="Identity, mission purpose, classification, releasability, compartment, entity sensitivity, and runtime health combine in fail-closed policy decisions adjacent to every protected operation.">
  <nav className="section-nav" aria-label="On this page"><a href="#access">Access control</a><a href="#provenance">Provenance</a><a href="#deployment">Deployment</a></nav>
  <SystemSection id="access" title="Coalition-aware access" intro="A visible UI is never an authorization boundary. APIs, ontology actions, search, caches, queues, and model context all enforce the same signed policy decision." items={[
    { title: "Strong identity", text: "Phishing-resistant operator authentication and audience-bound workload identity use short-lived, revocable credentials." }, { title: "Fine-grained policy", text: "ABAC combines tenant, mission, purpose, row, column, entity, compartment, classification, and releasability constraints." }, { title: "Coalition partitions", text: "Policy-filtered views and separate encryption contexts prevent cross-coalition retrieval, embeddings, caches, and context leakage." }, { title: "Break-glass", text: "Time-bounded emergency access requires explicit justification, elevated approval, prominent alerting, and mandatory after-action review." },
  ]} />
  <SystemSection id="provenance" title="Audit and provenance" intro="Material transitions emit privacy-aware records to an independently controlled, tamper-evident audit plane." items={[
    { title: "Decision identity", text: "Records bind actor, purpose, policy, data snapshot, retrieval set, model, prompt, tool calls, approval, result, and correlation ID." }, { title: "Integrity", text: "Canonical events are hash-linked, signed, access-controlled, retained by policy, time-correlated, and exported to immutable storage." }, { title: "Model governance", text: "Model cards, intended-use constraints, eval evidence, routing policy, prompt lineage, exceptions, owners, and expiry are versioned together." },
  ]} />
  <SystemSection id="deployment" title="Apollo release control" intro="Target environments accept only attested bundles that satisfy environment policy and named approval requirements." items={[
    { title: "Immutable bundle", text: "Application, ontology contract, policy, prompt, model route, eval report, SBOM, provenance, and rollback target share a release identity." }, { title: "Progressive delivery", text: "Development, evaluation, shadow, canary, and production stages have explicit promotion evidence and independent approval owners." }, { title: "Safe degradation", text: "Policy, identity, audit, lineage, or approval-service failure disables consequential execution and preserves read-only, marked-stale evidence where safe." },
  ]} />
</PageFlow>; }
