# Copyright (c) 2024-2026 ClearGlass Inc. All Rights Reserved.
# Proprietary and confidential. See LICENSE for terms.
"""Defender response layer — alerting.

Dispatches defender findings to the channels that are configured via environment
variables, and always writes an alert manifest to operations/output/defender/.

Channels (all optional, all off unless the env var is set):
  - GitHub Issue   GITHUB_TOKEN        — one incident issue for critical/high
  - Slack          SLACK_WEBHOOK_URL   — incoming-webhook summary
  - Discord        DISCORD_WEBHOOK_URL — webhook summary

Design constraints:
  - stdlib only (urllib), consistent with the rest of bots/.
  - Offline-safe: with no env vars set, this is a pure no-op that records what
    *would* have been sent. Tests run fully offline.
  - Never emits secret material — findings already carry redacted evidence.
"""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any
from urllib.error import URLError
from urllib.request import Request, urlopen

from bots.defender import policy as policy_mod

if TYPE_CHECKING:  # pragma: no cover - typing only, avoids an import cycle
    from bots.defender.engine import DefenderReport, Finding

ROOT = Path(__file__).resolve().parents[2]
OUTPUT_DIR = ROOT / "operations" / "output" / "defender"

GITHUB_REPO = "clearglassinc/clearglassinc.github.io"
GITHUB_API = "https://api.github.com"
_TIMEOUT = 15

_ICON = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🔵", "info": "⚪"}


def _now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def _alertable(report: "DefenderReport", policy: dict[str, Any]) -> list["Finding"]:
    """Findings whose severity is configured to raise an alert/issue."""
    gate = set(policy.get("enforcement", {}).get("open_issue_on", ["critical", "high"]))
    return [f for f in report.findings if f.severity in gate]


def _issue_title(findings: list["Finding"]) -> str:
    counts: dict[str, int] = {}
    for f in findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1
    parts = ", ".join(f"{counts[s]} {s}" for s in ("critical", "high", "medium") if counts.get(s))
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    return f"[DEFENDER] {parts} security finding(s) — {date}"


def _issue_body(report: "DefenderReport", findings: list["Finding"]) -> str:
    rows = "\n".join(
        f"| {_ICON.get(f.severity, '•')} {f.severity} | `{f.rule_id}` | "
        f"`{f.file}{f':' + str(f.line) if f.line else ''}` | {f.title} |"
        for f in findings
    )
    plan = "\n".join(f"- `{a}`" for a in report.response_plan) or "- _none_"
    return (
        "## 🛡️ ClearGlass Defender — security findings\n\n"
        f"- Run (UTC): `{report.run_utc}`\n"
        f"- Repository: `{report.repo}`\n"
        f"- Files scanned: {report.scanned_files}\n"
        f"- Build gate: {'❌ FAIL' if report.fail_build else '✅ pass'}\n\n"
        "### Findings\n\n"
        "| severity | rule | location | title |\n"
        "| --- | --- | --- | --- |\n"
        f"{rows}\n\n"
        "### Response plan\n\n"
        f"{plan}\n\n"
        "> Generated by `bots/defender`. Evidence for suspected secrets is redacted. "
        "Quarantine is advisory — enforce via branch protection and review.\n"
    )


def _post_json(url: str, payload: dict[str, Any], headers: dict[str, str]) -> bool:
    body = json.dumps(payload).encode("utf-8")
    req = Request(url, data=body, headers={"Content-Type": "application/json", **headers})
    try:
        with urlopen(req, timeout=_TIMEOUT) as resp:
            return 200 <= resp.status < 300
    except (URLError, OSError, ValueError):
        return False


def _create_github_issue(report: "DefenderReport", findings: list["Finding"]) -> bool:
    token = os.getenv("GITHUB_TOKEN", "").strip()
    if not token or not findings:
        return False
    payload = {"title": _issue_title(findings), "body": _issue_body(report, findings),
               "labels": ["security", "defender"]}
    return _post_json(
        f"{GITHUB_API}/repos/{GITHUB_REPO}/issues",
        payload,
        {
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": "clearglass-defender",
        },
    )


def _summary_text(report: "DefenderReport", findings: list["Finding"]) -> str:
    s = report.summary
    top = "; ".join(
        f"{_ICON.get(f.severity, '•')} {f.severity} {f.rule_id} @ {f.file}"
        for f in findings[:5]
    )
    return (
        f"🛡️ ClearGlass Defender — critical={s['critical']} high={s['high']} "
        f"medium={s['medium']} (gate: {'FAIL' if report.fail_build else 'pass'})\n{top}"
    )


def _notify_slack(text: str) -> bool:
    url = os.getenv("SLACK_WEBHOOK_URL", "").strip()
    return _post_json(url, {"text": text}, {}) if url else False


def _notify_discord(text: str) -> bool:
    url = os.getenv("DISCORD_WEBHOOK_URL", "").strip()
    return _post_json(url, {"content": text}, {}) if url else False


def dispatch(report: "DefenderReport", policy: dict[str, Any] | None = None) -> dict[str, Any]:
    """Send alerts for alertable findings and write the alert manifest.

    Returns a manifest describing which channels fired. With no channel env vars
    configured this is a no-op that still records the intended alert set.
    """
    policy = policy or policy_mod.load_policy()
    findings = _alertable(report, policy)
    should_alert = bool(findings)

    issue_created = _create_github_issue(report, findings) if should_alert else False
    summary = _summary_text(report, findings) if should_alert else ""
    slack_sent = _notify_slack(summary) if should_alert else False
    discord_sent = _notify_discord(summary) if should_alert else False

    manifest: dict[str, Any] = {
        "run_utc": _now(),
        "alertable_findings": len(findings),
        "channels": {
            "github_issue": issue_created,
            "slack": slack_sent,
            "discord": discord_sent,
        },
        "findings": [
            {"rule_id": f.rule_id, "severity": f.severity, "file": f.file, "line": f.line}
            for f in findings
        ],
    }

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUTPUT_DIR / "alerts.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return manifest
